sudo: false
language: php
php:
<<<<<<< HEAD
=======
  - 7.1
>>>>>>> upstream/master
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
